package pl.codegym.task.task13.task1318;                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
import java.io.BufferedReader;                                                                                                                                                                                                                                                                                                                                                                                                                
import java.io.InputStreamReader;                                                                                                                                                                                                                                                                                                                                                                                                                
import java.util.Scanner;                                                                                                                                                                                                                                                                                                                                                                                                                
import java.io.FileInputStream;                                                                                                                                                                                                                                                                                                             
import java.io.FileNotFoundException;                                                                                                                                                                                                                                                                                                                                                                                                               
import java.io.IOException;                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                               
/*                                                                                                                                                                                                                                                                                                                                                                                                                 
Wczytywanie pliku                                                                                                                                                                                                                                                                                                                                                                                                                
*/                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                
public class Solution {                                                                                                                                                                                                                                                                                                                                                                                                                
    public static void main(String[] args) throws IOException {                                                                                                                                                                                                                                                                                                                                                                                                                
        // tutaj wpisz swój kod                                                                                                                                                                                                                                                                                                            
    BufferedReader reader=new BufferedReader(new InputStreamReader(System.in));                                                                                                                                                                                                                                                                                                            
    String nazwa=reader.readLine();                                                   
    FileInputStream inStream=new FileInputStream(nazwa);                                                                                                                                                                                                                                                          
                                                       
 BufferedReader buffer=new BufferedReader(new InputStreamReader(inStream));                                                  
     String line;                                                                                                                                                                                                                                                                                                  
      while((line=buffer.readLine())!=null){                                                                                                                                                                                                                                                                                                            
                                                                                                                                                            
        System.out.println(line);                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                          
      }                                                                                                                                                       
      // System.out.println("");                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                
         reader.close();                                                                                                                                                                                                                                                                                               
        inStream.close();                                                                                                                                                                                                        
        buffer.close();                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                           
    }                                                                                                                                                                                                                                                                                                                                                                                                                
}